version: "3.7"

services:
  db:
    build: 
      ./db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data/
  movies_app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - web-static:/app/staticfiles
    depends_on:
      - db 
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-static:/app/staticfiles
    depends_on:
      - movies_app
      - db
  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
  etl:
    build:
      ./postgres_to_es
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 5s
    depends_on:
      - db
      - elasticsearch
    env_file:
      - ./.env
    volumes:
      - ./postgres_to_es/volumes/:/sites/states/
    

volumes:
  web-static: